version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      typescript-tooling:
        dependency-type: development
        patterns:
          - 'typescript'
          - 'typescript-eslint'
          - '@typescript-eslint/*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
