import type { PuzzleBoard } from '../types'

export const reactorCoolingEasy: PuzzleBoard = {
  id: 'reactor-cooling-easy-1',
  name: 'Reactor Cooling Failure',
  rows: 3,
  columns: 3,
  source: { row: 0, column: 0 },
  reactor: { row: 2, column: 2 },
  tiles: [
    {
      id: 'source',
      row: 0,
      column: 0,
      shape: 'endpoint',
      role: 'source',
      initialOrientation: 1,
      solutionOrientation: 1,
    },
    {
      id: 'top-straight',
      row: 0,
      column: 1,
      shape: 'straight',
      initialOrientation: 0,
      solutionOrientation: 1,
    },
    {
      id: 'top-corner',
      row: 0,
      column: 2,
      shape: 'corner',
      initialOrientation: 2,
      solutionOrientation: 2,
    },
    {
      id: 'middle-corner-left',
      row: 1,
      column: 0,
      shape: 'corner',
      initialOrientation: 0,
      solutionOrientation: 1,
    },
    {
      id: 'middle-straight',
      row: 1,
      column: 1,
      shape: 'straight',
      initialOrientation: 1,
      solutionOrientation: 1,
    },
    {
      id: 'middle-corner-right',
      row: 1,
      column: 2,
      shape: 'corner',
      initialOrientation: 3,
      solutionOrientation: 3,
    },
    {
      id: 'bottom-corner',
      row: 2,
      column: 0,
      shape: 'corner',
      initialOrientation: 0,
      solutionOrientation: 0,
    },
    {
      id: 'bottom-straight',
      row: 2,
      column: 1,
      shape: 'straight',
      initialOrientation: 0,
      solutionOrientation: 1,
    },
    {
      id: 'reactor',
      row: 2,
      column: 2,
      shape: 'endpoint',
      role: 'reactor',
      initialOrientation: 3,
      solutionOrientation: 3,
    },
  ],
}
